name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          ls -la
          pip install -r requirements.txt

      - name: Lint with Pylint
        run: |
          pip install pylint
          pylint SmartEnergy_DevOps-1/*.py

      - name: Test with Pytest
        run: |
          pip install pytest
          pytest test_*.py
